module.exports = {
    NODE_PORT:3000,
    SECRET_KEY: 'wL6kUhgYo/4?)F@%40;9rsMJs{h`.hI|4oT/`mJ"EE|Vw#kjH?FRE{vYWC<^;=t',
    TOKEN_SECRET:'gPlki9&nhg^gfrT5kIHgFe@dR#3fbgHy^KJnh98l*sPTn#A@2lf',
    OTP:'123456',
    HOST:"localhost",
    MYSQL_USER:"root",
    PASSWORD:"root",
    DB:"user_onboarding",
    PORT:3306,
    DIALECT:"mysql",
    MAX:50,
    MIN:0,
    ACQUIRE:30000,
    IDLE:10000,
    SWAGGER_HOST:"localhost:3000",
    limit:20,
    page:1,
    defaultLanguaueCode : 'en',
    defaultLanguageId : 1,
}